graphql:
  servlet:
    mapping: /graphql
    enabled: true

graphiql:
  enabled: true
  mapping: /graphiql
  endpoint: /graphql  
---
spring:
    profiles: tomcat-dev
graphql:
  servlet:
    mapping: /graphql
    enabled: true
#server:
#   servlet:
#      path: /sdfasfasdfadsfasdfasdfasfasf
graphiql:
  enabled: true
  mapping: /graphiql
  endpoint: /graphql_spring_boot_tutorial/graphql
